version: "3.3"
services:
  web1: 
    image: nginx
    ports:
      - "8080:80"
    volumes: 
      - "./build/:/usr/share/nginx/html/"
  web2:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - "./build/:/usr/share/nginx/html/"
